#!/bin/bash

# Build the executables with coverage options
make

# Now run them
./fizzbuzzTest
./fizzbuzzMain
./fizzbuzzMain 1 3
./fizzbuzzMain str 3

# Now produce the coverage reports
gcov -bar *.cpp

# Now show the overall coverage
gcovr
